# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
# POST {{baseUrl}}/rooms/{{roomId}}/questions
POST {{baseUrl}}/rooms/6f05315b-1442-4bfa-af46-cf39d951f59e/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}